### ISSUE TITLE
Use same controls as in the client editor

### ISSUE THREAD

**Issue by ChillerDragon** [k2d222/twwe#10]
Instead of space to place tiles use left click. And instead of moving the view with drag use ctrl+drag.

**Comment by ChillerDragon** [comment]
My bad seems like this is already the case.

**Comment by ChillerDragon** [comment]
Oh wait no. It is double click instead of single click to place a tile. What is the reasoning behind that? To not conflict with navigation?

**Comment by k2d222** [comment]
Some code was taken from another project. Any mouse button will place a tile but it is not working very well (atm click duration must be < 100ms, to avoid conflict with drag). This needs fixing.
Also the spacebar btn was added to allow placing multiple tiles by holding it, but I think it would be easier and more intuitive indeed with the controls from tw's map editor.
