### ISSUE TITLE
Is the .parcel-cache tracked in git intentionally?

### ISSUE THREAD

**Issue by ChillerDragon** [k2d222/twwe#35]
https://github.com/k2d222/twwe/tree/26e879f0896cf30c2d4de0fee906b160015a835f/client/.parcel-cache

One probably does not want to track that cache

**Comment by k2d222** [comment]
oh no lets get rid of it

**Comment by k2d222** [comment]
fixed by [3b28f5f](https://github.com/k2d222/twwe/commit/3b28f5f531ca58021a726a7da8e93bf69b34e38f)
