### ISSUE TITLE
Add tooltip bar for control hints

### ISSUE THREAD

**Issue by ChillerDragon** [k2d222/twwe#36]
I think the tooltip hint bar from the client editor would also be a nice to have here. Explaining the controls.
![Untitled](https://user-images.githubusercontent.com/20344300/170862558-9521c9fa-923a-4d7a-851b-6530eb1fbb25.png)

**Comment by k2d222** [comment]
It's a great idea! Do you want to implement this?

**Comment by ChillerDragon** [comment]
Oke ill give it a try

**Comment by k2d222** [comment]
nice. If you need help e.g. with svelte just ask ;) you should create a statusbar.svelte component and add it to editor.svelte :)
