### ISSUE TITLE
Who is catching all my keystrokes and is it needed?

### ISSUE THREAD

**Issue by ChillerDragon** [k2d222/twwe#37]
I really like my browser hotkeys `alt` to switch tabs `ctrl+shift+c` to open dev console. They both seem to be swallowed.
Is this intentional?

**Comment by k2d222** [comment]
unintentional and currently being fixed (like, right now)

**Comment by k2d222** [comment]
[47f76e1](https://github.com/k2d222/twwe/pull/34/commits/47f76e1d81389398bd0d6e829d39de6c02c6afca) fixed this.
