### ISSUE TITLE
Try to implement it in to a client as Editor server.

### ISSUE THREAD

**Issue by PotatoCreator** [k2d222/twwe#70]
This project is awesome! I enjoyed it a lot. Many of features are missing, but idea is to create an function to create an editor server in which you could give an connecting credentials to your friend so he could connect to your project.

**Comment by k2d222** [comment]
thanks for your feedback!
that would be awesome and it has been requested already by others. That would require some thought to smplify how to set up a server at home. Also, I would like to add a "choose server url" input on the homepage to switch between remotes, and possibly bundle the editor as a standalone app in addition to the website.

Sadly, I haven't been able to find much time to work on the project lately, but I hope to get back to it soon :)

**Comment by PotatoCreator** [comment]
Hope to see you soon! Your project is awesome!
