### ISSUE TITLE
Cursors of others has a offset

### ISSUE THREAD

**Issue by ChillerDragon** [k2d222/twwe#80]
I had the same map in two browser tabs open and the other persons cursor was displayed like 5 tiles further to the right and bottom than it actually was.

My cursor is on the single tile:

![image](https://github.com/user-attachments/assets/8dc8387e-96d3-4793-889e-18ece92de2eb)

**Comment by k2d222** [comment]
did you select the same group/layer in both instances? if a group has parallax then the cursor will appear in the location with parallax applied.

**Comment by ChillerDragon** [comment]
yes same group and layer
